- hosts: localhost
  tasks:
    - name: Copy a file to managed hosts
      ansible.builtin.copy:
        src: "/var/lib/awx/projects/_21__copy_check/copy.yml"
        dest: "/tmp"
      
    - name: Install the latest fireeye
      ansible.builtin.shell:
        cmd: echo "hello"
