- hosts: localhost
  tasks:
    - name: Copy a file to managed hosts
      ansible.builtin.copy:
        src: "/tmp/prasad"
        dest: "/tmp/neha"
      delegate_to: 10.74.255.16
    - name: Install the latest fireeye
      ansible.builtin.shell:
        cmd: tar -xvf  /tmp/f.tar
