- hosts: localhost
  tasks:
    - name: Copy a file to managed hosts
      ansible.builtin.copy:
        src: "/opt/f.tar"
        dest: "/tmp"
      delegate_to: 10.74.255.16
      
    - name: Install the latest fireeye
      ansible.builtin.shell:
        cmd: echo "hello"
